#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: Supabase project setup for team-planner.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5
ENV_FILE=".env.local"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

banner "team-planner: Supabase setup"

# ── Stage 1: create the project ────────────────────────────────────────────
stage "Create a Supabase project"
say "This app has no server of its own - Supabase is the database it talks"
say "to directly from the browser. You'll create a free project for it."
open_url "https://supabase.com/dashboard/projects"
step "Sign in (or sign up) if prompted."
step "Click 'New project'. Pick an organization (or create one)."
step "Name it something like 'team-planner'."
step "Set a database password - generate/save one, you won't need it again"
step "for this app (it isn't used anywhere below), but Supabase requires it."
step "Pick the region closest to you, then create the project."
note "Provisioning takes 1-2 minutes."
pause "Press Enter once the project's dashboard has finished loading."

# ── Stage 2: capture API credentials ───────────────────────────────────────
stage "Get the Project URL and anon key"
say "In the left sidebar: Project Settings -> API."
step "Under 'Project URL', copy the URL (https://<ref>.supabase.co)."
ask VITE_SUPABASE_URL "Paste the Project URL:"
step "Under 'Project API keys', copy the 'anon' / 'public' key (not service_role)."
note "This key is meant to end up public - the app ships it in its client"
note "bundle by design (see docs/adr/0001-no-auth-persistence-model.md)."
note "Hidden entry here is just to avoid it lingering in shell history/scrollback."
ask_secret VITE_SUPABASE_ANON_KEY "Paste the anon/public key:"
write_env VITE_SUPABASE_URL "$VITE_SUPABASE_URL"
write_env VITE_SUPABASE_ANON_KEY "$VITE_SUPABASE_ANON_KEY"

# ── Stage 3: run the schema ────────────────────────────────────────────────
stage "Run the database schema"
say "This creates the plans/plan_secrets tables and the RPC functions"
say "(get_plan, get_plan_names, create_plan, update_plan, delete_plan)"
say "that the app uses for every read and write - see supabase/schema.sql."
step "In the dashboard sidebar: SQL Editor -> New query."
step "Paste in the contents of supabase/schema.sql, printed below, then Run."
printf '\n%s%s\n' "$DIM" "$(cat "$REPO_ROOT/supabase/schema.sql")"
printf '%s\n' "$RESET"
pause "Press Enter once it ran successfully (no red error banner)."

# ── Stage 4: verify end to end ─────────────────────────────────────────────
stage "Verify it end to end"
say "In another terminal, from $REPO_ROOT, run:"
step "npm run dev"
step "Open the printed local URL (usually http://localhost:5173)."
step "Create a plan (any name), add a person with a capacity, add a ticket"
step "with an estimate, and check it off."
step "Refresh the browser tab."
if confirm "Did the plan's data still show after the refresh?"; then
  say "That confirms Supabase read/write is working end to end."
else
  warn "Something's off. Double-check VITE_SUPABASE_URL/ANON_KEY in $ENV_FILE"
  warn "match the project from stage 1, and that stage 3's SQL ran clean."
fi

# ── Stage 5: optional - wire up GitHub Pages deploy ────────────────────────
stage "Optional: enable the GitHub Pages deploy workflow"
say ".github/workflows/deploy.yml already reads these two values as repo"
say "secrets, so it can build the live site with your Supabase project."
if confirm "Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY as GitHub secrets now?"; then
  set_secret VITE_SUPABASE_URL "$VITE_SUPABASE_URL"
  set_secret VITE_SUPABASE_ANON_KEY "$VITE_SUPABASE_ANON_KEY"
  note "Also set repo Settings -> Pages -> Source to 'GitHub Actions' if you"
  note "haven't already - the workflow needs that to actually publish."
else
  say "Skipped - see README.md 'Deploying to GitHub Pages' to do this later."
fi
# ──────────────────────────────────────────────────────────────────────────

finish
